name: build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # get entire git tree, required for nerdbank gitversioning
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1.1
      with:
        keyvault: "ActionsBuild"
        secrets: 'NuGetUsername, NuGetPassword, NuGetEndpoint'
      id: azureSecrets
    - name: Build project
      shell: pwsh
      run: ./build.ps1
    - name: Push it to NuGet
      run: |
        dotnet nuget add source --store-password-in-clear-text --name Target "${{ steps.azureSecrets.outputs.NuGetEndpoint }}"
        dotnet nuget push --skip-duplicate '.build/packages/*.nupkg' -k "${{ steps.azureSecrets.outputs.NuGetPassword }}" -s Target
